name: 🐞 Report a bug or error
description: Report an error or unexpected behavior with the project or module in this repository.
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug ONLY if it is related to the project repo.
      
      - For more than one bug report please submit them separately.
      - Add any screenshots that could help understand your feature request (you can copy/paste images in the feature request box)

- type: input
  id: module
  validations:
    required: true
  attributes:
    label: Module
    description: |
        Which project module are you talking about
        
        Use the project and module name or URL. 

- type: markdown
  attributes:
    value: |
      Provide a concise description of what the bug is. 
      
      **Do not attach ZIP files** - instead, please post a shared link to it.

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Describe the observed behavior
    placeholder: Tell us what you see!
  validations:
    required: true

- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    description: Describe steps to reproduce the issue
    value: |
      1.
      2.
      3.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: What did you expect to happen when the reproduce steps are followed?
    placeholder: Tell us what you expected to see!
  validations:
    required: true

- type: checkboxes
  id: client
  attributes:
    label: Client    
    description: |
      What client have you tested where this issue occurs?
      
      Select the clients this submission is relevant to.

    options:
      - label: desktop client
      - label: Web browser
      - label: mobile (iOS/iPad OS)
      - label: mobile (Android)
      - label: not applicable
      - label: other (enter in the "Additional environment details" area below)

- type: dropdown
  id: environment-os
  attributes:
    label: Developer environment
    options:
      - Windows
      - macOS
      - Linux

- type: checkboxes
  id: browsers
  attributes:
    label: Browsers    
    description: |
      What browser(s) / client(s) have you tested
      
      Select the browser(s)/clients this submission is relevant to.

    options:
      - label: Internet Explorer
      - label: Microsoft Edge
      - label: Google Chrome
      - label: FireFox
      - label: Safari
      - label: mobile (iOS/iPadOS)
      - label: mobile (Android)
      - label: not applicable
      - label: other (enter in the "Additional environment details" area below)

- type: input
  id: Node
  validations:
    required: true
  attributes:
    label: Node.js version
    placeholder: v16
    description: |
        Which version of Node.js are you using?
        
        TIP: To find out, run `node -v`

- type: textarea
  id: moreinfo
  attributes:
    label: Additional environment details
    description: Include as much detail about the environment you're targeting. This is required if "other (enter below)" is selected in the previous field.
